# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: b5af8b3469cda8a526e167040539f7de289c25399ed74363e9b23882d75b67fea5924372d6c7fa2fbfe3885f22fe9411496f7bf2dbb31a029e8e4bfc713426d6

test:
  secret_key_base: d5500cc5dc45097e0fb5c1478c1d103d93d892309f0a3d686d967305ca6aceb9371b5de7aae73f3d72fd4dc70a9e661b56057bcf4efcb473df4ccf1dce3ff449

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
